### ISSUE TITLE
The module should specify dependency to protobuf >3.7.1

### ISSUE THREAD

**Issue by llali** [onnx/onnx#3134]
The module doesn't work with protobuf 3.7.1. If user has that version already, the following script fails:
import onnx
print(onnx.TensorProto.DataType.FLOAT)

Error: 'EnumTypeWrapper' object  has no attribute 'FLOAT' 

Updating protobuf to 3.12.2 fixes the issue.

**Comment by jcwchen** [comment]
Will be solved by this: https://github.com/onnx/onnx/pull/3499. Thanks!
