### ISSUE TITLE
Failed Linux CI (Azure Pipeline)

### ISSUE THREAD

**Issue by wschin** [onnx/onnx#2972]
All Azure CIs fail for some unknown reasons in https://github.com/onnx/onnx/pull/2966 and some other PRs. Here is a screenshot for the status. 

![image](https://user-images.githubusercontent.com/3524474/91211185-33c85680-e6c3-11ea-997d-880a8a0131e6.png)

If we look into its log, we can see some missing definitions like

```
onnx/__init__.py:104: error: Name 'ModelProto' is not defined
onnx/__init__.py:129: error: Name 'TensorProto' is not defined
onnx/__init__.py:144: error: Name 'ModelProto' is not defined
onnx/__init__.py:155: error: Name 'ModelProto' is not defined
onnx/__init__.py:158: error: Name 'TensorProto' is not defined
onnx/__init__.py:169: error: Name 'TensorProto' is not defined
onnx/__init__.py:172: error: Name 'ModelProto' is not defined
```

Since Travis Linux CIs are all passed and that PR was good before sync with master, I guess Azure CIs might have some problems.

**Comment by jcwchen** [comment]
Hi @wschin,
I encounter the same error in my PR. Even if I rerun the master commit, it will also encounter this error.
The error occurs here in Linux CIs:
`ONNX_NAMESPACE=ONNX_NAMESPACE_FOO_BAR_FOR_CI pip install --no-use-pep517 -e .[mypy]`
I am digging into this issue. Thank you for reporting this.

**Comment by jcwchen** [comment]
It has been fixed in https://github.com/onnx/onnx/pull/2974. Thank you.
