### ISSUE TITLE
ONNX Build fails on Ubuntu 24.04 LTS and python 3.13

### ISSUE THREAD

**Issue by bakas-george** [onnx/onnx#6883]
# Bug Report

### Describe the bug

The onnx package fails to install and compile on systems running Ubuntu 24.04 with Python 3.13, while the same setup works fine with Python 3.12. This issue does not occur on Ubuntu 20.04 with Python 3.13, indicating a compatibility issue specific to the Ubuntu 24.04 + Python 3.13 combination.

### System information

- OS Platform and Distribution: Linux Ubuntu 24.04 LTS
- ONNX version: 1.17
- Python Version(s): 3.12, 3.13
- CMake: 4.0.0
- Protobuf version: 4.22.3 (we also upgraded with no success)

### Reproduction instructions
 

Steps to Reproduce:

* Create a virtual env (we used both `uv` and `venv` with Python 3.13 on Ubuntu 24.04
* Attempt to install onnx via pip or from source.
* Observe the build/compilation errors

**Comment by justinchuby** [comment]
You can test the rc1 at https://test.pypi.org/project/onnx/1.18.0rc1/
