### ISSUE TITLE
namespace on onnx.proto is conflict with the onnx code 

### ISSUE THREAD

**Issue by qzhong0605** [onnx/onnx#2477]
When I built onnx from scratch through `CMake`, it reported errors about the types on `onnx.pb.h` were not defined. They were the following: 
```
include/onnx/defs/shape_inference.h:721:5: error: ‘Dim’ has not been declared

onnx/include/onnx/defs/shape_inference.h:742:22: error: ‘Dim’ was not declared in this scope
``` 
I found that the namespace was `ONNX_NAMESPACE` on `onnx/defs/shape_inference.h`, while the namespace was `onnx` on `onnx.pb.h`. 

In order to build onnx with `CMakeLists.txt`, a variable `ONNX_NAMESPACE` was set to `onnx`,
which was not consistent the namespace on `shape_inference.h`.

If I built the onnx with the following command, it would be ok. 
```
 cmake -DBUILD_SHARED_LIBS=ON -DONNX_ML=OFF -DONNX_BUILD_TESTS=ON -DPROTO3_ENABLED=ON -DONNX_BUILD_BENCHMARKS=ON -DONNX_NAMESPACE=ONNX_NAMESPACE ../
```

Is it a good choice to support `ONNX_NAMESPACE` setting on `onnx.in.proto`? If it's allowed, the code using types on `onnx.in.proto`  needs to be modified at the same time.

**Comment by linkerzhang** [comment]
thanks a lot for bringing this up. This was introduced by PR https://github.com/onnx/onnx/pull/526. @bddppq may help to add comments.

**Comment by qzhong0605** [comment]
Thanks.
