### ISSUE TITLE
error: no member named 'has_ref_attr_name' in 'onnx::AttributeProto'

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx#841]
I got an error as title from checker.cc#L223 `if (used_fields != 1 && (used_fields != 0 || !attr.has_ref_attr_name())) {`
which is introduced by https://github.com/onnx/onnx/pull/802
@linkerzhang Did I miss something?
