### ISSUE TITLE
pypi version requires protobuf 3.4

### ISSUE THREAD

**Issue by dougalsutherland** [onnx/onnx#639]
Because `sdist` includes `onnx.pb.h`, the generated source distribution can only be used with the same(ish) version of `protobuf` as whoever generated the source. Particularly, `pip install onnx` doesn't work right now if you have protobuf 3.5.

Since you need protobuf at compile time anyway, it'd probably be better to change `setup.py` to not include these files in `sdist`s but generate them at compile time instead....

**Comment by bddppq** [comment]
1. including the auto-generated `onnx.pb.h` file is not ok, since pypi doesn't allow reuse the version number, we need to bump the version again v1.1.1

2. `sdist` should not auto-generate the protobuf header files. I just tried again locally and it matches my expectation. The current situation is very likely the release process is done in a not clean git checkout (i.e. the auto-generated files are already there). @anirudhacharya to confirm.

**Comment by anirudhacharya** [comment]
@bddppq Before pushing to the dist, I did check that my git checkout was clean, with this
```
git diff --exit-code || echo "Nope"
```
And it was clean.

**Comment by dougalsutherland** [comment]
@anirudhacharya That doesn't tell you anything about gitignored files, including `onnx.pb.h`. `git clean -nxd` or similar would be a better approach.

**Comment by anirudhacharya** [comment]
Yes, the checkout was probably not clean.
```
Would remove onnx/onnx-operators.pb.cc
Would remove onnx/onnx-operators.pb.h
Would remove onnx/onnx.pb.cc
Would remove onnx/onnx.pb.h
Would remove onnx/onnx_operators_pb.py
Would remove onnx/onnx_operators_pb2.py
Would remove onnx/onnx_pb.py
Would remove onnx/onnx_pb.pyc
Would remove onnx/onnx_pb2.py
Would remove onnx/onnx_pb2.pyc
```
we could probably run, ```git clean -xd``` and push the 1.1.1 release.

**Comment by anirudhacharya** [comment]
@bddppq @dougalsutherland 
I can ```git clean -xd``` my branch to remove all the build products from the branch, then I will generate the source distribution, and push to the test instance of pypi. We can test it and then make the v1.1.1 release to pypi.
Would that be okay?

**Comment by dougalsutherland** [comment]
SGTM @anirudhacharya.

**Comment by HeliWang** [comment]
For now if I want to build and install from the master source, which version of protobuf should I use? I was using protobuf master version but I got:

   gcc -pthread -B /home/ubuntu/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DONNX_NAMESPACE=onnx -I/tmp/pip-k3xe161w-build -I/tmp/pip-k3xe161w-build/third_party/pybind11/include -I/home/ubuntu/anaconda3/include/python3.6m -I/home/ubuntu/anaconda3/include/python3.6m -c /tmp/pip-k3xe161w-build/onnx/checker.cc -o build/temp.linux-x86_64-3.6/tmp/pip-k3xe161w-build/onnx/checker.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /tmp/pip-k3xe161w-build/onnx/onnx_pb.h:64:0,
                     from /tmp/pip-k3xe161w-build/onnx/checker.h:6,
                     from /tmp/pip-k3xe161w-build/onnx/checker.cc:1:
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:250:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:577:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:725:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:956:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:1186:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:1322:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:1523:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:1643:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:1987:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:2123:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:2238:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:2365:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:2488:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
       static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
              ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:5585:115: error: expected class-name before ‘{’ token
     template <> struct is_proto_enum< ::onnx::AttributeProto_AttributeType> : ::google::protobuf::internal::true_type {};
                                                                                                                       ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:5590:107: error: expected class-name before ‘{’ token
     template <> struct is_proto_enum< ::onnx::TensorProto_DataType> : ::google::protobuf::internal::true_type {};
                                                                                                               ^
    /tmp/pip-k3xe161w-build/onnx/onnx.pb.h:5595:94: error: expected class-name before ‘{’ token
     template <> struct is_proto_enum< ::onnx::Version> : ::google::protobuf::internal::true_type {};
                                                                                                  ^
    error: command 'gcc' failed with exit status 1

**Comment by anirudhacharya** [comment]
@HeliWang use this - https://github.com/google/protobuf/releases/tag/v3.4.0

**Comment by bddppq** [comment]
@HeliWang If you want to install from the current github master, the issue mentioned above doesn't affect you, you can use any version that is >=2.6.1 If you want to install the current newest release from pypi, then use the one pointed by @anirudhacharya .

**Comment by bddppq** [comment]
@anirudhacharya this is because the autogenerated files are in git ignored. The safest way is do a clean checkout.
Note this won't be a problem once our release automation setup is ready (@raymondxyang is working on that).

**Comment by anirudhacharya** [comment]
@dougalsutherland @bddppq published v1.1.1 to testpypi. 
Seems to work fine with the protobuf version 2.6.1. I am trying with libprotoc 3.5. I will comment here once I have verified.
```
# protoc --version
libprotoc 2.6.1
```
```
:~# pip install --index-url https://test.pypi.org/simple/ onnx
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting onnx
  Downloading https://test-files.pythonhosted.org/packages/41/ff/9dedf5ec330be64c6c5f7b13e31d7ff674eb3525a2cc73c9f605fedb2e84/onnx-1.1.1.tar.gz (940kB)
    100% |████████████████████████████████| 942kB 1.8MB/s 
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from onnx)
Requirement already satisfied: protobuf in /usr/local/lib/python2.7/dist-packages (from onnx)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from onnx)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf->onnx)
Installing collected packages: onnx
  Running setup.py install for onnx ... done
Successfully installed onnx-1.1.1
```

**Comment by HeliWang** [comment]
I am trying to install the onnx-1.1.0 version from pip. Before the pip installation I have installed protobuf 3.4.0 from https://github.com/google/protobuf/releases/tag/v3.4.0 as well as the protobuf python v3.4.0.

Right now if I check the protoc version by "protoc --version", it will show as libprotoc 3.4.0.

However after I did "pip install onnx" I got the same error like:

gcc -pthread -B /home/ubuntu/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DONNX_NAMESPACE=onnx -I/tmp/pip-k3xe161w-build -I/tmp/pip-k3xe161w-build/third_party/pybind11/include -I/home/ubuntu/anaconda3/include/python3.6m -I/home/ubuntu/anaconda3/include/python3.6m -c /tmp/pip-k3xe161w-build/onnx/checker.cc -o build/temp.linux-x86_64-3.6/tmp/pip-k3xe161w-build/onnx/checker.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /tmp/pip-k3xe161w-build/onnx/onnx_pb.h:64:0,
from /tmp/pip-k3xe161w-build/onnx/checker.h:6,
from /tmp/pip-k3xe161w-build/onnx/checker.cc:1:
/tmp/pip-k3xe161w-build/onnx/onnx.pb.h:250:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
^
/tmp/pip-k3xe161w-build/onnx/onnx.pb.h:577:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
^

Am I missing anything? Like setting PROTOBUF_INCDIR and CONDA_PREFIX?
I am using Ubuntu 14.04 and anaconda 5.1 (python 3.6).

I have been trying to install the onnx v1.1 from morning today. Appreciate if you can help. Thanks.

**Comment by anirudhacharya** [comment]
Built and installed [protobuf 3.5.0](https://github.com/google/protobuf/releases/tag/v3.5.0), commit hash - https://github.com/google/protobuf/commit/2761122b810fe8861004ae785cc3ab39f384d342

and 

Built and installed [protobuf 3.5.1](https://github.com/google/protobuf/releases/tag/v3.5.1), commit hash - https://github.com/google/protobuf/commit/106ffc04be1abf3ff3399f54ccf149815b287dd9
```
:~# protoc --version
libprotoc 3.5.1
```
Was able to compile and install onnx v1.1.1 as below.
```
:~# pip install --index-url https://test.pypi.org/simple/ onnx
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting onnx
  Downloading https://test-files.pythonhosted.org/packages/41/ff/9dedf5ec330be64c6c5f7b13e31d7ff674eb3525a2cc73c9f605fedb2e84/onnx-1.1.1.tar.gz (940kB)
    100% |████████████████████████████████| 942kB 1.7MB/s 
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from onnx)
Requirement already satisfied: protobuf in /usr/local/lib/python2.7/dist-packages (from onnx)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from onnx)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf->onnx)
Installing collected packages: onnx
  Running setup.py install for onnx ... done
Successfully installed onnx-1.1.1
```
But when I try to run ONNX tests, it encounters errors. @dougalsutherland @bddppq can one of you confirm this. These tests run fine with ```libprotoc 2.6.1``` the errors are only when I use ```libprotoc 3.5.*```
```
# pytest tests/python-pytest/onnx/onnx_backend_test.py 
============================================================== test session starts ===============================================================
platform linux2 -- Python 2.7.12, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/ubuntu/incubator-mxnet, inifile:
plugins: cov-2.5.1
collected 0 items / 1 errors                                                                                                                     

===================================================================== ERRORS =====================================================================
_________________________________________ ERROR collecting tests/python-pytest/onnx/onnx_backend_test.py _________________________________________
tests/python-pytest/onnx/onnx_backend_test.py:26: in <module>
    import onnx.backend.test
/usr/local/lib/python2.7/dist-packages/onnx/__init__.py:6: in <module>
    from .onnx_pb import *  # noqa
/usr/local/lib/python2.7/dist-packages/onnx/onnx_pb.py:8: in <module>
    from .onnx_pb2 import *  # noqa
/usr/local/lib/python2.7/dist-packages/onnx/onnx_pb2.py:23: in <module>
    serialized_pb=_b('\n\nonnx.proto\x12\x04onnx\"\xc9\x03\n\x0e\x41ttributeProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ndoc_string\x18\r \x01(\t\x12\x30\n\x04type\x18\x14 \x01(\x0e\x32\".onnx.AttributeProto.AttributeType\x12\t\n\x01\x66\x18\x02 \x01(\x02\x12\t\n\x01i\x18\x03 \x01(\x03\x12\t\n\x01s\x18\x04 \x01(\x0c\x12\x1c\n\x01t\x18\x05 \x01(\x0b\x32\x11.onnx.TensorProto\x12\x1b\n\x01g\x18\x06 \x01(\x0b\x32\x10.onnx.GraphProto\x12\x0e\n\x06\x66loats\x18\x07 \x03(\x02\x12\x0c\n\x04ints\x18\x08 \x03(\x03\x12\x0f\n\x07strings\x18\t \x03(\x0c\x12\"\n\x07tensors\x18\n \x03(\x0b\x32\x11.onnx.TensorProto\x12 \n\x06graphs\x18\x0b \x03(\x0b\x32\x10.onnx.GraphProto\"\x91\x01\n\rAttributeType\x12\r\n\tUNDEFINED\x10\x00\x12\t\n\x05\x46LOAT\x10\x01\x12\x07\n\x03INT\x10\x02\x12\n\n\x06STRING\x10\x03\x12\n\n\x06TENSOR\x10\x04\x12\t\n\x05GRAPH\x10\x05\x12\n\n\x06\x46LOATS\x10\x06\x12\x08\n\x04INTS\x10\x07\x12\x0b\n\x07STRINGS\x10\x08\x12\x0b\n\x07TENSORS\x10\t\x12\n\n\x06GRAPHS\x10\n\"Q\n\x0eValueInfoProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x04type\x18\x02 \x01(\x0b\x32\x0f.onnx.TypeProto\x12\x12\n\ndoc_string\x18\x03 \x01(\t\"\x96\x01\n\tNodeProto\x12\r\n\x05input\x18\x01 \x03(\t\x12\x0e\n\x06output\x18\x02 \x03(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07op_type\x18\x04 \x01(\t\x12\x0e\n\x06\x64omain\x18\x07 \x01(\t\x12\'\n\tattribute\x18\x05 \x03(\x0b\x32\x14.onnx.AttributeProto\x12\x12\n\ndoc_string\x18\x06 \x01(\t\"\x93\x02\n\nModelProto\x12\x12\n\nir_version\x18\x01 \x01(\x03\x12.\n\x0copset_import\x18\x08 \x03(\x0b\x32\x18.onnx.OperatorSetIdProto\x12\x15\n\rproducer_name\x18\x02 \x01(\t\x12\x18\n\x10producer_version\x18\x03 \x01(\t\x12\x0e\n\x06\x64omain\x18\x04 \x01(\t\x12\x15\n\rmodel_version\x18\x05 \x01(\x03\x12\x12\n\ndoc_string\x18\x06 \x01(\t\x12\x1f\n\x05graph\x18\x07 \x01(\x0b\x32\x10.onnx.GraphProto\x12\x34\n\x0emetadata_props\x18\x0e \x03(\x0b\x32\x1c.onnx.StringStringEntryProto\"4\n\x16StringStringEntryProto\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xea\x01\n\nGraphProto\x12\x1d\n\x04node\x18\x01 \x03(\x0b\x32\x0f.onnx.NodeProto\x12\x0c\n\x04name\x18\x02 \x01(\t\x12&\n\x0binitializer\x18\x05 \x03(\x0b\x32\x11.onnx.TensorProto\x12\x12\n\ndoc_string\x18\n \x01(\t\x12#\n\x05input\x18\x0b \x03(\x0b\x32\x14.onnx.ValueInfoProto\x12$\n\x06output\x18\x0c \x03(\x0b\x32\x14.onnx.ValueInfoProto\x12(\n\nvalue_info\x18\r \x03(\x0b\x32\x14.onnx.ValueInfoProto\"\xaf\x04\n\x0bTensorProto\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x03\x12-\n\tdata_type\x18\x02 \x01(\x0e\x32\x1a.onnx.TensorProto.DataType\x12*\n\x07segment\x18\x03 \x01(\x0b\x32\x19.onnx.TensorProto.Segment\x12\x16\n\nfloat_data\x18\x04 \x03(\x02\x42\x02\x10\x01\x12\x16\n\nint32_data\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x13\n\x0bstring_data\x18\x06 \x03(\x0c\x12\x16\n\nint64_data\x18\x07 \x03(\x03\x42\x02\x10\x01\x12\x0c\n\x04name\x18\x08 \x01(\t\x12\x12\n\ndoc_string\x18\x0c \x01(\t\x12\x10\n\x08raw_data\x18\t \x01(\x0c\x12\x17\n\x0b\x64ouble_data\x18\n \x03(\x01\x42\x02\x10\x01\x12\x17\n\x0buint64_data\x18\x0b \x03(\x04\x42\x02\x10\x01\x1a%\n\x07Segment\x12\r\n\x05\x62\x65gin\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\"\xcc\x01\n\x08\x44\x61taType\x12\r\n\tUNDEFINED\x10\x00\x12\t\n\x05\x46LOAT\x10\x01\x12\t\n\x05UINT8\x10\x02\x12\x08\n\x04INT8\x10\x03\x12\n\n\x06UINT16\x10\x04\x12\t\n\x05INT16\x10\x05\x12\t\n\x05INT32\x10\x06\x12\t\n\x05INT64\x10\x07\x12\n\n\x06STRING\x10\x08\x12\x08\n\x04\x42OOL\x10\t\x12\x0b\n\x07\x46LOAT16\x10\n\x12\n\n\x06\x44OUBLE\x10\x0b\x12\n\n\x06UINT32\x10\x0c\x12\n\n\x06UINT64\x10\r\x12\r\n\tCOMPLEX64\x10\x0e\x12\x0e\n\nCOMPLEX128\x10\x0f\"\x81\x01\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x01 \x03(\x0b\x32 .onnx.TensorShapeProto.Dimension\x1a>\n\tDimension\x12\x13\n\tdim_value\x18\x01 \x01(\x03H\x00\x12\x13\n\tdim_param\x18\x02 \x01(\tH\x00\x42\x07\n\x05value\"\xa3\x01\n\tTypeProto\x12-\n\x0btensor_type\x18\x01 \x01(\x0b\x32\x16.onnx.TypeProto.TensorH\x00\x1a^\n\x06Tensor\x12-\n\telem_type\x18\x01 \x01(\x0e\x32\x1a.onnx.TensorProto.DataType\x12%\n\x05shape\x18\x02 \x01(\x0b\x32\x16.onnx.TensorShapeProtoB\x07\n\x05value\"5\n\x12OperatorSetIdProto\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03*c\n\x07Version\x12\x12\n\x0e_START_VERSION\x10\x00\x12\x19\n\x15IR_VERSION_2017_10_10\x10\x01\x12\x19\n\x15IR_VERSION_2017_10_30\x10\x02\x12\x0e\n\nIR_VERSION\x10\x03')
E   TypeError: __new__() got an unexpected keyword argument 'serialized_options'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================ 1 error in 0.07 seconds =============================================================
```

**Comment by dougalsutherland** [comment]
@anirudhacharya Not sure where these tests are? If I run `python setup.py test` on a clean checkout of the `v1.1.0` tag, I get lots of `ModuleNotFoundError: No module named 'onnx.version'` errors. But those file paths don't look like anything I'm seeing in the `onnx` repo.

**Comment by anirudhacharya** [comment]
@dougalsutherland sorry for the confusion, those were a bunch of mxnet tests that uses ONNX, please disregard those error messages. 

I have pushed v1.1.1 to test PyPi - https://test.pypi.org/simple/onnx/ 
I am able to install onnx v1.1.1 with ```pip install --index-url https://test.pypi.org/simple/ onnx==1.1.1```  with protoc versions ```libprotoc 3.5.1``` and ```libprotoc 2.6.1```.

Can you please confirm that the v1.1.1 release on testPyPi is all good. And I will go ahead and push the   distribution to Pypi.

**Comment by dougalsutherland** [comment]
I am also able to `pip install --index-url https://test.pypi.org/simple/ onnx==1.1.1` with `libprotoc 3.5.1` on OSX. Don't have any actual test cases handy to run and check, though.

**Comment by anirudhacharya** [comment]
I am able to build and compile the v1.1.1 tag with protobuf version 2.6, 3.4 and 3.5.1. I think this distribution is fine. Doing a ```git clean -ixd``` before building the sdist ensured that my branch was clean and that I was not pushing any files generated as part of the local build into PyPi.

The distribution is currently on the test instance of PyPi and can be installed with ```pip install --index-url https://test.pypi.org/simple/```. 

I will push the v1.1.1 distribution to PyPi tomorrow morning.
cc: @dougalsutherland @bddppq

**Comment by HeliWang** [comment]
I disabled conda and now I am able to build and compile the v1.1.1 tag with protobuf version 2.6.1.

**Comment by anirudhacharya** [comment]
ONNX v1.1.1 release - https://pypi.org/project/onnx/
