### PR TITLE
Fix Windows Release CI failure due to unresolved external symbol

### PR DESCRIPTION
**Pull request by jcwchen**
### Description

Fix Windows Release CI failure : `onnx.lib(checker.obj) : error LNK2001: unresolved external symbol "public: int __thiscall google::protobuf::RepeatedField<int>::size(void)const " (?size@?$RepeatedField@H@protobuf@google@@QBEHXZ) [D:\a\onnx\onnx\onnx\.setuptools-cmake-build\onnx_cpp2py_export.vcxproj]` by setting PATH properly. We should use prepend instead of append.

### Motivation and Context

Try to fix https://github.com/onnx/onnx/issues/5659. Currently Windows Release CI starts to fail after https://github.com/onnx/onnx/pull/5596.

### CODE REVIEW

**Review by jcwchen — COMMENTED** [review]
Share more findings:
- It only happened on x86 Windows machine.
- The failure might be not related to https://github.com/onnx/onnx/pull/5596, because in that commit some x86 machines did pass CI (which uses `Version: 20230924.1.0`).
- Something might be changed from the Windows machine -- from `Version: 20230924.1.0` to `Version: 20231002.1.0`

**Review by justinchuby — APPROVED** [review]

**Review by jcwchen — COMMENTED** [review]
Thanks @liqunfu for finding out there is a new introduced library: `libprotobuf-lite` from MySQL server. In practice we should "prepend" the manually installed Protobuf path instead of "append". It can reduce conflict if there are multiple installed Protobuf.

**Review by liqunfu — APPROVED** [review]
