### ISSUE TITLE
How to add custom hardware support

### ISSUE THREAD

**Issue by jadoro** [onnx/onnx#2293]
Hi,

I'm working for a hardware vendor who would like to support ONNX on a custom hardware accelerator for low energy matrix multiplication.

This accelerator is supposed to be used for inference as well as during the forward pass of all training steps.

Given the multiple frameworks available, I'm confused how such integration is supposed to be done. So far I've found at least three different ways to integrate vendor/accelerator specific devices:

* Implement an [`onnx.Backend`](https://github.com/onnx/onnx/blob/master/docs/ImplementingAnOnnxBackend.md)
* Implement an [`ExecutionProvider`](https://github.com/microsoft/onnxruntime/blob/master/docs/AddingExecutionProvider.md) in [`onnxruntime`](https://github.com/microsoft/onnxruntime)
* Provide an implementation of [`ONNXIFI`](https://github.com/onnx/onnx/blob/master/docs/ONNXIFI.md)

I would appreciate any input on the different use cases and intentions of these interfaces, especially in the context of training directly on the accelerator.

Thanks a lot in advance!
jadoro

**Comment by prasanthpul** [comment]
Great question.

- onnx.backend is a simple Python interface that is useful for model-level testing of different engines. onnxruntime exposes [this interface](https://microsoft.github.io/onnxruntime/auto_examples/plot_backend.html) as well
- ONNXIFI is a specification for an interface for offloading ONNX graphs or subgraphs to accelerators. onnxruntime does not implement ONNXIFI 1.0. The Arch&Infra SIG has a backlog item to work on ONNXIFI 2.0. 
- onnxruntime aims to support all ONNX operators on CPU and uses ExecutionProvider to delegate subgraphs to accelerators. you should consider implementing an ExecutionProvider for your custom hardware accelerator so that customers can still run any ONNX model with ONNX Runtime but get the benefit of your accelerator on the ops/models that you support.

**Comment by askhade** [comment]
Closing this now since Prasanth addressed all the questions. @jadoro : If you still have more questions please open a new issue. Thanks!
